[package]
name = "refactor-tool-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
refactor_tool = { path = ".." }

[[bin]]
name = "fuzz_parse_rust"
path = "fuzz_targets/fuzz_parse_rust.rs"
test = false
doc = false